source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
  gem 'zurb-foundation', '~> 4.0.0'
  
  gem 'jquery-rails'
  gem 'ember-rails'
  gem 'ember-source', '1.0.0.rc6.2'
  gem 'handlebars-source'
end